// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrRH9I-80dbeAs-3f3hAf_ee8gHCn8c6M',
    appId: '1:992594773020:android:54d9056bf4a6519d1ecbd9',
    messagingSenderId: '992594773020',
    projectId: 'food-delivery-app-c7313',
    storageBucket: 'food-delivery-app-c7313.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsAqHPWr1AGvMSEGdQq5Z-bZJfdbq8kes',
    appId: '1:992594773020:ios:6ccdf387f6eadab81ecbd9',
    messagingSenderId: '992594773020',
    projectId: 'food-delivery-app-c7313',
    storageBucket: 'food-delivery-app-c7313.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg9qA8Z_fKCFhROmLCOyL9mEeBFDto4Qg',
    appId: '1:992594773020:web:99a19a61f5a8cb681ecbd9',
    messagingSenderId: '992594773020',
    projectId: 'food-delivery-app-c7313',
    authDomain: 'food-delivery-app-c7313.firebaseapp.com',
    storageBucket: 'food-delivery-app-c7313.firebasestorage.app',
    measurementId: 'G-JTS9LW040F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsAqHPWr1AGvMSEGdQq5Z-bZJfdbq8kes',
    appId: '1:992594773020:ios:6ccdf387f6eadab81ecbd9',
    messagingSenderId: '992594773020',
    projectId: 'food-delivery-app-c7313',
    storageBucket: 'food-delivery-app-c7313.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg9qA8Z_fKCFhROmLCOyL9mEeBFDto4Qg',
    appId: '1:992594773020:web:0b45ec9065ecabc01ecbd9',
    messagingSenderId: '992594773020',
    projectId: 'food-delivery-app-c7313',
    authDomain: 'food-delivery-app-c7313.firebaseapp.com',
    storageBucket: 'food-delivery-app-c7313.firebasestorage.app',
    measurementId: 'G-SK846EVRM1',
  );

}